// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Atika",
    "email": "atikalestari8498@gmail.com",
    "password": "1234678",
    "confPassword": "12345678",
    "role": "admin"
}

###
// get All Users
GET http://locaalhost:5000/users

###
//Get Single User
GET http://localhost:5000/users/

### 
// Update a user
PATCH  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Atika Updated",
    "email": "atikalestari8498@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// deleted user
DELETE   http://localhost:5000/users

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "admin@gmail.com",
    "password": "1234678",
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "yaatikaok@gmail.com",
    "password": "1234678",
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/loguot

### Get All Product
GET http://locaalhost:5000/users


### Post Data Product 
POST http://localhost:5000/products
Content-Type: application/json

{
   
    "name": "Product A",
    "price": "999",
}